# Generated by Django 4.2.7 on 2025-11-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0002_dailyentry_expense_physicalactivity_taskdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(),
        ),
    ]
